// The spinner's vocabulary, lifted from Claude Code (constants/spinnerVerbs.ts)
// so the cockpit's live line reads like the harness it drives. One verb per
// run, not per frame: a word that changes while you read it is noise, and the
// operator watches several runs at once.
//
// Ink-free, like the rest of model/: the spinner needs the word, and the
// suite needs to measure the line without a renderer.

export const SPINNER_VERBS: string[] = [
  "Accomplishing",
  "Actioning",
  "Actualizing",
  "Architecting",
  "Baking",
  "Beaming",
  "Bootstrapping",
  "Brewing",
  "Burrowing",
  "Calculating",
  "Cascading",
  "Cerebrating",
  "Channeling",
  "Choreographing",
  "Churning",
  "Clauding",
  "Coalescing",
  "Cogitating",
  "Combobulating",
  "Composing",
  "Computing",
  "Concocting",
  "Considering",
  "Contemplating",
  "Cooking",
  "Crafting",
  "Creating",
  "Crunching",
  "Crystallizing",
  "Cultivating",
  "Deciphering",
  "Deliberating",
  "Determining",
  "Doing",
  "Elucidating",
  "Envisioning",
  "Fermenting",
  "Flowing",
  "Forging",
  "Forming",
  "Generating",
  "Germinating",
  "Harmonizing",
  "Hashing",
  "Hatching",
  "Herding",
  "Ideating",
  "Imagining",
  "Improvising",
  "Incubating",
  "Inferring",
  "Infusing",
  "Kneading",
  "Manifesting",
  "Marinating",
  "Mulling",
  "Mustering",
  "Musing",
  "Nesting",
  "Noodling",
  "Orbiting",
  "Orchestrating",
  "Percolating",
  "Perusing",
  "Pollinating",
  "Pondering",
  "Processing",
  "Proofing",
  "Propagating",
  "Puzzling",
  "Reticulating",
  "Ruminating",
  "Seasoning",
  "Simmering",
  "Sketching",
  "Spelunking",
  "Spinning",
  "Sprouting",
  "Stewing",
  "Swirling",
  "Synthesizing",
  "Tempering",
  "Thinking",
  "Tinkering",
  "Transfiguring",
  "Transmuting",
  "Unfurling",
  "Unravelling",
  "Vibing",
  "Wandering",
  "Whirring",
  "Whisking",
  "Working",
  "Wrangling",
];

/**
 * The verb a run keeps for its whole life. Deliberately a pure function of the
 * id rather than a random draw: the spinner is rebuilt on every reconnect and
 * every re-render, and a word that resampled itself would flicker.
 */
export function verbFor(id: number): string {
  const n = SPINNER_VERBS.length;
  const i = ((Math.trunc(id) % n) + n) % n;
  return SPINNER_VERBS[i] as string;
}
