#!/usr/bin/env bash
# Install task-orchestrator as a systemd service and grant the service
# user passwordless sudo to manage it.
#
# Run as root:
#   sudo bash scripts/install-service.sh
#
# Overridable via env vars:
#   SERVICE_USER   (default: claude)        — runs the Next.js process
#   APP_DIR        (default: this repo)     — WorkingDirectory for the unit
#   DATA_DIR       (default: /var/lib/task-orchestrator) — SQLite + assets
#
# Idempotent: re-run after editing this script to update the unit / sudoers.

set -euo pipefail

if [[ ${EUID} -ne 0 ]]; then
  echo "error: must run as root (try: sudo bash $0)" >&2
  exit 1
fi

SERVICE_USER="${SERVICE_USER:-claude}"
APP_DIR="${APP_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
DATA_DIR="${DATA_DIR:-/var/lib/task-orchestrator}"
UNIT_PATH="/etc/systemd/system/task-orchestrator.service"
SUDOERS_PATH="/etc/sudoers.d/claude-task-orchestrator"
ENV_FILE="${APP_DIR}/.env.local"

SYSTEMCTL="$(command -v systemctl)"
JOURNALCTL="$(command -v journalctl)"
if [[ -z "${SYSTEMCTL}" || -z "${JOURNALCTL}" ]]; then
  echo "error: systemctl/journalctl not found in PATH" >&2
  exit 1
fi

if ! id "${SERVICE_USER}" >/dev/null 2>&1; then
  echo "error: user '${SERVICE_USER}' does not exist" >&2
  exit 1
fi

SERVICE_HOME="$(getent passwd "${SERVICE_USER}" | cut -d: -f6)"
NVM_SH="${SERVICE_HOME}/.nvm/nvm.sh"
if [[ -f "${NVM_SH}" ]]; then
  EXEC_START="/bin/bash -c '. ${NVM_SH} && exec npm run start'"
  echo "→ detected nvm at ${NVM_SH}; sourcing it from the unit"
else
  EXEC_START="/usr/bin/env npm run start"
  echo "→ no nvm detected; assuming npm is on the system PATH"
fi

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "warning: ${ENV_FILE} not found — service will fail to start until you create it" >&2
fi

# Gather extra paths the service needs write access to beyond APP_DIR/DATA_DIR.
# These come from two sources, in order:
#   1. TASK_ORCH_TARGET_REPO from .env.local (legacy single-repo deployments).
#   2. Every repositories.local_path from the SQLite data.db (multi-repo).
# Duplicates are collapsed.
declare -A SEEN_RW=()
EXTRA_RW=""
add_rw() {
  local path="$1"
  [[ -z "${path}" ]] && return
  if [[ -z "${SEEN_RW[$path]:-}" ]] && [[ -d "${path}" ]]; then
    SEEN_RW[$path]=1
    EXTRA_RW+=" ${path}"
    echo "→ ${path} → ReadWritePaths"
  elif [[ ! -d "${path}" ]]; then
    echo "warning: ${path} is not a directory; skipping" >&2
  fi
}

TARGET_REPO=""
if [[ -f "${ENV_FILE}" ]]; then
  TARGET_REPO="$(grep -E '^TASK_ORCH_TARGET_REPO=' "${ENV_FILE}" | head -1 | cut -d= -f2- | tr -d '"' | tr -d "'")"
fi
[[ -n "${TARGET_REPO}" ]] && add_rw "${TARGET_REPO}"

# Pull local_path values from the SQLite DB. Locate the DB via TASK_ORCH_DB in
# the env file, falling back to the conventional location.
DB_PATH=""
if [[ -f "${ENV_FILE}" ]]; then
  DB_PATH="$(grep -E '^TASK_ORCH_DB=' "${ENV_FILE}" | head -1 | cut -d= -f2- | tr -d '"' | tr -d "'")"
fi
[[ -z "${DB_PATH}" ]] && DB_PATH="${DATA_DIR}/data.db"

if [[ -f "${DB_PATH}" ]]; then
  SQLITE3="$(command -v sqlite3 || true)"
  if [[ -n "${SQLITE3}" ]]; then
    while IFS= read -r path; do
      [[ -n "${path}" ]] && add_rw "${path}"
    done < <("${SQLITE3}" "${DB_PATH}" "SELECT local_path FROM repositories WHERE local_path IS NOT NULL AND local_path != '';" 2>/dev/null || true)
  else
    echo "note: sqlite3 not installed — skipping per-repository ReadWritePaths discovery" >&2
  fi
fi

# 1. Data directory
echo "→ ensuring ${DATA_DIR} (owned by ${SERVICE_USER})"
install -d -o "${SERVICE_USER}" -g "${SERVICE_USER}" -m 0755 "${DATA_DIR}"

# 2. Systemd unit
echo "→ writing ${UNIT_PATH}"
cat > "${UNIT_PATH}" <<UNIT
[Unit]
Description=Task Orchestrator (Next.js)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${SERVICE_USER}
Group=${SERVICE_USER}
WorkingDirectory=${APP_DIR}
EnvironmentFile=${ENV_FILE}
ExecStart=${EXEC_START}
Restart=on-failure
RestartSec=5s

# Hardening — orchestrator needs app dir + data dir writable. The Claude
# Agent SDK writes to ~/.claude.json via atomic rename (tempfile → rename),
# which breaks systemd's per-file bind mounts on the next write. We expose
# the whole service-user home dir instead so directory bind mounts survive
# atomic writes; other users' homes stay read-only.
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=read-only
ReadWritePaths=${APP_DIR} ${DATA_DIR} ${SERVICE_HOME}${EXTRA_RW}
PrivateTmp=true

[Install]
WantedBy=multi-user.target
UNIT
chmod 0644 "${UNIT_PATH}"

# 3. Sudoers drop-in — scoped to this one unit + log tail
echo "→ writing ${SUDOERS_PATH}"
cat > "${SUDOERS_PATH}" <<SUDO
# Auto-generated by scripts/install-service.sh — edit there, not here.
${SERVICE_USER} ALL=(root) NOPASSWD: ${SYSTEMCTL} start task-orchestrator, \\
                                    ${SYSTEMCTL} stop task-orchestrator, \\
                                    ${SYSTEMCTL} restart task-orchestrator, \\
                                    ${SYSTEMCTL} reload task-orchestrator, \\
                                    ${SYSTEMCTL} enable task-orchestrator, \\
                                    ${SYSTEMCTL} disable task-orchestrator, \\
                                    ${SYSTEMCTL} daemon-reload
${SERVICE_USER} ALL=(root) NOPASSWD: ${JOURNALCTL} -u task-orchestrator *
SUDO
chmod 0440 "${SUDOERS_PATH}"

echo "→ validating sudoers syntax"
if ! visudo -cf "${SUDOERS_PATH}" >/dev/null; then
  echo "error: sudoers validation failed — removing ${SUDOERS_PATH}" >&2
  rm -f "${SUDOERS_PATH}"
  exit 1
fi

# 4. Reload systemd so it sees the unit
echo "→ systemctl daemon-reload"
"${SYSTEMCTL}" daemon-reload

cat <<DONE

✓ Installed.

Service:  task-orchestrator.service
Unit:     ${UNIT_PATH}
Sudoers:  ${SUDOERS_PATH}
Data:     ${DATA_DIR}
Runs as:  ${SERVICE_USER}

Next steps (as ${SERVICE_USER}, no sudo password needed):
  cd ${APP_DIR}
  npm install
  npm run build
  sudo systemctl enable --now task-orchestrator
  sudo journalctl -u task-orchestrator -f
DONE
