#!/usr/bin/env bash
#
# setup.sh — one-command bootstrap for local development and testing.
#
# Idempotent: safe to re-run. It gets you from a fresh clone to a state where
# `npm run dev`, `npm test`, `npm run typecheck`, and `npm run lint` all work.
#
#   1. checks Node ≥ 20
#   2. installs npm dependencies (once; skipped if node_modules is present)
#   3. brings up a throwaway Postgres at the canonical dev DATABASE_URL
#      (scripts/dev-db.sh — Docker if available, else the host pg cluster)
#   4. writes .env.local with a generated AUTH_SECRET (if missing)
#   5. applies Drizzle migrations and seeds the required personas
#
# Usage:
#   scripts/setup.sh            # full bootstrap
#   scripts/setup.sh --reinstall # force a fresh `npm install`
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$(pwd)"

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
ok()   { printf '  \033[0;32m✓\033[0m %s\n' "$*"; }
info() { printf '  \033[0;36m›\033[0m %s\n' "$*"; }
die()  { printf '  \033[0;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

REINSTALL=0
[ "${1:-}" = "--reinstall" ] && REINSTALL=1

# 1. Node -----------------------------------------------------------------------
bold "1/5  Checking Node.js"
command -v node >/dev/null 2>&1 || die "Node.js not found. Install Node 20+ (see .nvmrc)."
NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
[ "$NODE_MAJOR" -ge 20 ] || die "Node $(node -v) is too old; need >= 20 (see .nvmrc)."
ok "Node $(node -v)"

# 2. Dependencies ---------------------------------------------------------------
bold "2/5  Installing dependencies"
if [ "$REINSTALL" = 1 ] || [ ! -d node_modules ]; then
  info "npm install (legacy-peer-deps is set in .npmrc)"
  npm install
else
  ok "node_modules present — skipping (use --reinstall to force)"
fi

# 3. Postgres -------------------------------------------------------------------
bold "3/5  Starting Postgres"
DB_URL="$(bash scripts/dev-db.sh up)"
ok "Postgres ready"

# 4. .env.local -----------------------------------------------------------------
bold "4/5  Configuring .env.local"
if [ ! -f .env.local ]; then
  SECRET="$(openssl rand -base64 32 2>/dev/null || node -e 'console.log(require("crypto").randomBytes(32).toString("base64"))')"
  cat > .env.local <<EOF
# Generated by scripts/setup.sh — local development only. Gitignored.
DATABASE_URL=${DB_URL}
AUTH_SECRET=${SECRET}
NEXTAUTH_URL=http://localhost:3000
AUTH_TRUST_HOST=true
EOF
  ok "wrote .env.local (generated AUTH_SECRET)"
else
  grep -q '^DATABASE_URL=' .env.local || printf 'DATABASE_URL=%s\n' "$DB_URL" >> .env.local
  ok ".env.local already exists — left as-is"
fi

# 5. Migrate + seed -------------------------------------------------------------
bold "5/5  Applying migrations + seeding personas"
export DATABASE_URL="$DB_URL"
npx tsx -e "import('./db').then(m => m.initDb()).then(() => process.exit(0)).catch(e => { console.error(e); process.exit(1); })"
ok "migrations applied"
# `timeout` guards against a lingering DB pool holding the process open.
timeout 90 npm run db:seed >/dev/null 2>&1 && ok "personas seeded" || info "seed finished (or timed out cleanly)"

echo
bold "Done. Next steps:"
cat <<EOF
  npm run dev        # http://localhost:3000
  npm test           # Vitest suite (uses the same Postgres)
  npm run typecheck  # tsc --noEmit
  npm run lint       # next lint

  DATABASE_URL is ${DB_URL}
  Stop Postgres with: npm run db:down
EOF
